

spring:
  # 数据库连接
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti-demo?useSSL=false&characterEncoding=utf-8
    username: wking
    password: king
  # 配置jpa
  jpa:
    hibernate.ddl-auto: update
    database: mysql
    show-sql: true
  freemarker:
    suffix: .html

#mybaits配置
mybatis:
  type-aliases-package: top.kylewang.pojo
  mapper-locations: classpath:mappers/*.xml